# Generated by Django 2.1 on 2018-03-23 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='cp',
            field=models.IntegerField(choices=[(1, 'typical angina'), (2, 'atypical angina'), (3, 'non-anginal pain'), (4, 'asymptomatic')], default=1),
        ),
        migrations.AddField(
            model_name='data',
            name='exang',
            field=models.IntegerField(choices=[(1, 'yes'), (0, 'no')], default=1, max_length=1),
        ),
        migrations.AddField(
            model_name='data',
            name='fbs',
            field=models.IntegerField(choices=[(1, 'fasting blood sugar > 120 mg/dl'), (0, 'fasting blood sugar < 120 mg/dl')], default=1),
        ),
        migrations.AddField(
            model_name='data',
            name='restecg',
            field=models.IntegerField(choices=[(0, 'normal '), (1, 'having ST-T wave abnormality'), (2, 'showing probable ')], default=0),
        ),
        migrations.AddField(
            model_name='data',
            name='sex',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1),
        ),
        migrations.AddField(
            model_name='data',
            name='slope',
            field=models.IntegerField(choices=[(1, 'upsloping'), (2, 'flat'), (3, 'downsloping')], default=1, max_length=1),
        ),
        migrations.AddField(
            model_name='data',
            name='thal',
            field=models.IntegerField(choices=[(3, 'normal'), (6, 'fixed defect'), (7, 'reversable defect')], default=3, max_length=1),
        ),
    ]
