# Generated by Django 2.1 on 2018-03-23 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20180323_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='exang',
            field=models.IntegerField(choices=[(1, 'yes'), (0, 'no')], default=1),
        ),
        migrations.AlterField(
            model_name='data',
            name='slope',
            field=models.IntegerField(choices=[(1, 'upsloping'), (2, 'flat'), (3, 'downsloping')], default=1),
        ),
        migrations.AlterField(
            model_name='data',
            name='thal',
            field=models.IntegerField(choices=[(3, 'normal'), (6, 'fixed defect'), (7, 'reversable defect')], default=3),
        ),
    ]
